#!/usr/bin/env python

# import all of the apps

from msmaccelerator.model.modeler import Modeler
from msmaccelerator.server.adaptiveserver import AdaptiveServer

from msmaccelerator.core.app import RootApplication
from msmaccelerator.simulate.simulation import Simulator
from msmaccelerator.core.mkprofile import MKProfile
from msmaccelerator.interact.interactor import Interactor

def main():
    # register all of the apps as subcommands
    app = RootApplication.instance()
    app.register_subcommand(AdaptiveServer, Modeler, Simulator, MKProfile,
                            Interactor)
    app.initialize()
    app.start()

if __name__ == '__main__':
    main()
    
